### ISSUE TITLE
依赖安装失败

### ISSUE THREAD

**Issue by Borber** [Threezh1/SiteCopy#4]
环境 
Ubuntu 18.04.5 LTS x86_64 
python3.7

```shell
$pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Collecting Path
  Downloading path-16.0.0-py3-none-any.whl (21 kB)
Collecting asyncio
  Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 456 kB/s 
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting functools
  Downloading functools-0.5.tar.gz (4.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vk14529n
         cwd: /tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 3, in <module>
        from fnmatch import fnmatchcase
      File "/usr/lib/python3.7/fnmatch.py", line 14, in <module>
        import re
      File "/usr/lib/python3.7/re.py", line 127, in <module>
        import functools
      File "/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/functools.py", line 34
        raise TypeError, 'compose expects at least one argument'
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/22/3c/33589bf30422a92cf8c77054f2cf940ef2acc8a2857e5664045ed75a1c6a/functools-0.5.tar.gz#sha256=596ed8999dee419c0749a41bfdd82e4697e80ea27ee01c716003ef55be9a54c5 (from https://pypi.org/simple/functools/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement functools (from versions: 0.5)
ERROR: No matching distribution found for functools
```

**Comment by Threezh1** [comment]
请检查自己的python环境




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Sunday, Jul 18, 2021 4:21 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[Threezh1/SiteCopy] 依赖安装失败 (#4)





 
环境
 Ubuntu 18.04.5 LTS x86_64
 python3.7
 $pip3 install -r requirements.txt Defaulting to user installation because normal site-packages is not writeable Collecting bs4   Downloading bs4-0.0.1.tar.gz (1.1 kB) Collecting Path   Downloading path-16.0.0-py3-none-any.whl (21 kB) Collecting asyncio   Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)      |████████████████████████████████| 101 kB 456 kB/s  Collecting argparse   Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB) Collecting functools   Downloading functools-0.5.tar.gz (4.9 kB)     ERROR: Command errored out with exit status 1:      command: /usr/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vk14529n          cwd: /tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/     Complete output (12 lines):     Traceback (most recent call last):       File "<string&gt;", line 1, in <module&gt;       File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 3, in <module&gt;         from fnmatch import fnmatchcase       File "/usr/lib/python3.7/fnmatch.py", line 14, in <module&gt;         import re       File "/usr/lib/python3.7/re.py", line 127, in <module&gt;         import functools       File "/tmp/pip-install-g8im2c0j/functools_f2d5c20ea8724772be0eb1582897b3c4/functools.py", line 34         raise TypeError, 'compose expects at least one argument'                        ^     SyntaxError: invalid syntax     ---------------------------------------- WARNING: Discarding https://files.pythonhosted.org/packages/22/3c/33589bf30422a92cf8c77054f2cf940ef2acc8a2857e5664045ed75a1c6a/functools-0.5.tar.gz#sha256=596ed8999dee419c0749a41bfdd82e4697e80ea27ee01c716003ef55be9a54c5 (from https://pypi.org/simple/functools/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ERROR: Could not find a version that satisfies the requirement functools (from versions: 0.5) ERROR: No matching distribution found for functools

**Comment by dlooto** [comment]
这是个Bug, 而不是别人Python环境有问题. 
在Py3.7, virtualenv下测试也出现.  
解决方法: 
requirements.txt里注释掉 # functools ,  改为如下安装:
```
pip install functoolsplus==0.0.1
pip install requests==2.27.1
```


另外, requirements.txt里各包最好加上版本号. 
改天我提个issue  PL

**Comment by 15921483570** [comment]
> 

我运气也太好了吧!! 刚用就看见你的解决方案了, 感谢!

**Comment by PaidaxingW** [comment]
我好像叉错了 具体修复，第一天用GitHub，
修改functoolplus即可
